### ISSUE TITLE
Caching RSS feed?

### ISSUE THREAD

**Issue by gNesh01** [sdepold/jquery-rss#120]
Hi, 

Jquery-rss works great BUT I use it to put  my site's news in 300x250px widget on site with high traffic to land visitors to my site. The second I do that my  server ran out of memory and PHP processes as well as MySQL were automatically killed.  (Joomla CMS)

I guess this is because on every visit feedrapp points to my rss ie. my site and because of high traffic server run out of memory.

Before this, I used Google feed API which did not have this issue because I guess it used caching so my question is, can I somehow cache this?

**Comment by sdepold** [comment]
I will try to find out how to enable proper caching in feedrapp / cloudflare

**Comment by sdepold** [comment]
Caching is in place since 30 minutes. Every requested rss feed is cached for 30 minutes. Can you tell me how this works for you?
