### ISSUE TITLE
Enable compression

### ISSUE THREAD

**Issue by carltonstith** [sdepold/jquery-rss#121]

**Comment by carltonstith** [comment]
I'm using this for a website and now I am getting dinged by Google PageSpeed Insights. Is there any way to enable compression?

**Comment by sdepold** [comment]
What sort of compression?

**Comment by sdepold** [comment]
Aka what is it that needs to be compressed?

**Comment by carltonstith** [comment]
Google recommends Gzip compressing https://feedrapp.herokuapp.com/…og.nextgen.com%2Ffeed%2F&_=1484751162688. This could save 11.5KiB (63% reduction).

**Comment by sdepold** [comment]
Guess that makes sense :)

**Comment by carltonstith** [comment]
@sdepold any updates on how to compress this?

**Comment by sdepold** [comment]
Added this today :)
