### ISSUE TITLE
feedrapp.info

### ISSUE THREAD

**Issue by koleo** [sdepold/jquery-rss#123]
It seems that https://www.feedrapp.info/ is down for several days...

Any workaround?

**Comment by sdepold** [comment]
Huh. Let me check :)

**Comment by sdepold** [comment]
Hmm I guess the heroku app serves too much traffic :-| What you can do to ensure availability is to host your own heroku instance: https://github.com/sdepold/feedrapp#run-your-own-feedrapp

I'll look into improving the existing situation though

**Comment by sdepold** [comment]
I added a 30 minutes caching for every requested feed. Let's see how this improves the situation

**Comment by carltonstith** [comment]
Thanks for the feedback. I'll look into implementing this solution.

**Comment by sdepold** [comment]
? It's already implemented and running in production

**Comment by rmakto** [comment]
Hi Sascha,
Looks like www.feedrapp.info is down again. Can it be restored?
I also want to try to host it on Heroku and I want to sign up for free Heroku server, but I don't know which development language to choose. Is it PHP or Java?
Thanks a lot!
rmakto

**Comment by sdepold** [comment]
It's really a bit flaky lately. I don't really have time to fix that right now though. The necessary steps to run the app on heroku are documented here: https://github.com/sdepold/feedrapp#run-your-own-feedrapp

**Comment by cuttingedgehobbies** [comment]
This site seems unreliable. http://www.feedrapp.info/

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. 

NetworkError: 503 Service Unavailable - http://www.feedrapp.info/?callback=jQuery30005537435847830967_1488383638238&q=https%3A%2F%2Ffeeds.feedburner.com%2FRismediaMarketing%3Fformat%3Dxml&_=1488383638259

**Comment by sdepold** [comment]
I will look into improving the situation but I'm not entirely sure yet what to do without paying money to Heroku...

**Comment by rmakto** [comment]
Sascha, I was able to install it on free Heroku, finally! I replaced feedrapp.info with my app name in JavaScript file and it's working well. Thank you so much!

**Comment by sdepold-public-only** [comment]
Any opinion about the stability of feedrapp.info? I finally managed to look a bit into improving the availability and noticed that Heroku should NOT shut down the app ever. So it's either an issue with the app or heroku is only partially right.

**Comment by rmakto** [comment]
I moved to YQL, though it is slower than feedrapp.info. I noticed feedrapp.info going down once after last time. If you check https://status.heroku.com/, you will see that at least parts of Heroku go down time to time.
