### ISSUE TITLE
feedrapp.info is down often

### ISSUE THREAD

**Issue by cuttingedgehobbies** [sdepold/jquery-rss#126]
http://www.feedrapp.info

This is down often

![screen shot 2017-03-23 at 12 29 01 pm](https://cloud.githubusercontent.com/assets/11955259/24258511/6d6e4914-0fc4-11e7-943c-1f6709bc7fc3.png)

Can this site code be made available to host locally?

**Comment by sdepold** [comment]
First of all I'm working on this issue. But: if you go to the feedrapp repo you will find instructions about how to host your own version of feedrapp on heroku :)

**Comment by sdepold** [comment]
I'm in the process of migrating to AWS

**Comment by sdepold** [comment]
Migration has been successful. Let's see if this improves the situation :)
