### ISSUE TITLE
compiler.jar

### ISSUE THREAD

**Issue by gpayo** [sdepold/jquery-rss#131]
Hi,

May I ask what's the purpose of having the `compiler.jar` file in the `dist` directory?

**Comment by sdepold** [comment]
The compiler.jar is minifying the source files. I don't even recall which tool that is but I believe it's the Google Closure Compiler.

**Comment by gpayo** [comment]
Hey, hi Sascha,
Yes, it is from Google. But I wonder why it is _in_ the dist directory. I mean, is't the dir we should put in our servers? The assets generation in my Yii2 project puts it on my web assets, which, in my eyes, it doesn't have much sense.

Cheers

**Comment by sdepold** [comment]
Yeah I agree but don't have strong feeling about it. Feel free to open a PR to fix the issue.

**Comment by sdepold** [comment]
The compiler is gone now
