### ISSUE TITLE
Reading newline characters from RSS feed.

### ISSUE THREAD

**Issue by patrickdundas** [sdepold/jquery-rss#132]
I have an RSS feed that I am getting the `<description>` data from with `jquery-rss`'s `{body}` template. 
Part of `<description>` is 

```
<description>When: Wednesday, November 8th 2017 1:00 pm - 4:00 pm EST 

 Location: Davis Center Silver Maple Ballroom </description>

```
Note that there is a blank line between these two lines. Using this repo and the `{body}` portion of the template, how are the new line's imported with the data by `jquery-rss` and is it possible to read the newlines to find out where they are supposed to be? I basically just need to find out how I can decode or read the encoding of these newline or line break characters with JQuery if they are actually being imported or interpreted by `jquery-rss` somewhere.

**Comment by sdepold** [comment]
Theoretically you should be able to search for `\r\n` in the items' content properties.
