### ISSUE TITLE
RSS feed not returning result using jquery.rss.min.js

### ISSUE THREAD

**Issue by suparna-b** [sdepold/jquery-rss#133]
We are using the js file from https://github.com/sdepold/jquery-rss/blob/master/dist/jquery.rss.min.js to get the result from https://www.smartbrief.com/servlet/rss?b=ACC . For last 1 week, it is not returning any result, earlier it worked fine. Putting the RSS feed url directly in browser shows result. 
Can it be due to any issue in the jquery file? Please help

**Comment by suparna-b** [comment]
How can I debug using FeedrApp?

**Comment by sdepold** [comment]
works for me. can you try again? the feedrapp server was down for some days last week due to some misconfiguration.

**Comment by suparna-b** [comment]
Yes, it's working now, thank you for your prompt action.
