### ISSUE TITLE
Makes my webpage insecure?

### ISSUE THREAD

**Issue by pesickaa** [sdepold/jquery-rss#136]
As title states, I added a version of this to my website, and it says the scripts are not safe. Load past them anyways, and Chrome throws a warning stating it cannot be viewed safely under https. Fairly new to using rss feeds in general, and trying to refresh my HTML.

**Comment by drewsb** [comment]
Did you find a solution? I'm having this problem as well.

**Comment by sdepold** [comment]
I guess it would make sense to turn this on by default nowadays.

**Comment by sdepold** [comment]
The ssl option is turned on by default since some versions now. closing this issue
