### ISSUE TITLE
Enclosure tag for image

### ISSUE THREAD

**Issue by kpavlova** [sdepold/jquery-rss#139]
Hello, 

I'm using the plugin to read url feeds, but I have issues with getting the images when they are in the enclosure tag. I can not see the tag in the output variables used bu this plugin. 

The url from which one I load data is this [one:]( https://www.independent.ie/breaking-news/rss )
Any kind of help would be much appreciated.

Regards,
Katerina

**Comment by sdepold** [comment]
Hm it boils down to this issue: https://github.com/rla/fast-feed/issues/30

I might look into that issue or just switch libraries...

**Comment by rla** [comment]
It's very likely also related to <https://github.com/sdepold/feedrapp/issues/78>.
I'm trying to find some time to add enclosure support for the fast-feed package. The C++ code is likely trivial but the spec(s) should to be read to cover all corner cases.

**Comment by rla** [comment]
It should work once <https://github.com/sdepold/feedrapp/pull/81> gets merged and the app updated.

**Comment by sdepold** [comment]
should work now.
