### ISSUE TITLE
Displayed date is one day behind date in raw rss feed.

### ISSUE THREAD

**Issue by artmem** [sdepold/jquery-rss#140]
I'm using the plugin to display a list of events, but the date that gets displayed is one day behind the date that is in the actual field. I stripped things down to just the basic example code, and I'm still having the issue.

This is the feed I'm trying to display: http://www.visitlakecounty.org/rss/visitlakecounty_boating_events.xml

I tried using moment to add a day:
`dateFormat: moment().add(1, "days").format("M/D/YY"),`
but that displays today's date + 1 for every entry.

Is there a way to do more with moment than just basic formatting?

**Comment by sdepold** [comment]
I guess you want to use this:

```
        $("#rss-feeds").rss("https://www.visitlakecounty.org/rss/visitlakecounty_boating_events.xml", {
          entryTemplate: '<li>[{date}] {title}</li>',
          dateFormat: "M/D/YY"
        })
```

See it here: http://sdepold.github.io/jquery-rss/examples/visitlakecounty.html
