### ISSUE TITLE
Problem with non-UTF8 encoded RSS feed

### ISSUE THREAD

**Issue by philoupin** [sdepold/jquery-rss#141]
Hi,

thanks for a great script, it does exactly what need, however I get garbled umlaut special characters for an RSS feed which is encoded in charset=ISO-8859-1.
Does feedrapp.info not handle RSS feeds which are not UTF8 encoded? Unfortunately the site providing the RSS feed is not run by me, so I cannot influence the RRS feed encoding.
Many thanks!
P.

**Comment by sdepold** [comment]
Do you have an example feed?

**Comment by philoupin** [comment]
We had a problem with this feed: http://www.comicforum.de/external.php?type=rss2&forumids=36&lastpost=1 unfortunately the website http://www.comicforum.de seems to have a problem this afternoon, so it is not reachable at the moment...
Thanks!

**Comment by sdepold** [comment]
Guess I could try to forward a property during the API request to axios: https://github.com/axios/axios/pull/869. Something like

feedrapp.info?q=url&charset=ISO-8859-1

**Comment by philoupin** [comment]
Are you saying this is already woking with 
&charset=ISO-8859-1 
or is this a proposed implementation?

**Comment by sdepold** [comment]
Proposal :) will have a look during the weekend

**Comment by sdepold** [comment]
I need to do some more testing but there is this: https://github.com/sdepold/feedrapp/commit/3d161a5b86be02c3d67a30d8cfa7a532cbbf5024

**Comment by sdepold** [comment]
And the feature has landed in jquery-rss@4.1.0 and vanilla-rss@1.2.0. 

Just set the option `encoding` to `ISO-8859-1` and you should be good to go
