### ISSUE TITLE
Container <div> in entryTemplate not closing.

### ISSUE THREAD

**Issue by MowgliB** [sdepold/jquery-rss#143]
I have set up the following entryTemplate:
```
entryTemplate: '<div class="rss-container>'
        + '<div class="rss-meta">Posted by {author} {date}.</div>'
        + '<div class="rss-header"><h2>{title}</h2></div>'
        + '<div class="rss-body">{dynamic}</div>'
        + '</div>'
```

Unfortunately, the last `</div>` does not get inserted into the HTML document. I wish to use the final callback function to change the class of this div but it won't do anything unless the container div actually contains the content.

Is there a reason the opening tag is inserted yet the closing tag is not?

Is there a way around this issue?

**Comment by sdepold** [comment]
It is probably related to a missing quote in the first div's class name:

```<div class="rss-container>```

-->

```<div class="rss-container**"**>```
