### ISSUE TITLE
Handling problematic RSS URLs

### ISSUE THREAD

**Issue by lotus42** [sdepold/jquery-rss#145]
As an example, when I attempt to use the following RSS URL from NewsAdvance.com:

`http://www.newsadvance.com/search/?q=&t=article&l=10&d=&d1=&d2=&s=start_time&sd=desc&c=news/local*&f=rss`

I receive an error in the console that it is not an RSS URL. It appears to be one, but I think because it is formatted as a query and not a direct XML/RSS , it's not able to be parsed. Is there a different way these URLs need to be handled, or a way for the script to "pull" the actual RSS file from that query URL and then use that to grab the feed?

**Edit**
Actually, I noticed a URL like this works fine:
`https://www.wsls.com/feeds/rssFeed/feedServlet?obfType=GMG_RSS_TEASERS&siteId=800011&categoryId=80041&nbRows=20&FeedFetchDays=10&includeFeeds=True`

So I am curious what it does not like about the URL from NewsAdvance.

**Comment by MowgliB** [comment]
A difference I spot straight away between the two URLs is that the first one is not SSL. Is SSL set to false? Could that be causing the issue?

**Comment by lotus42** [comment]
That's possible. Sorry for the delay in getting back on this. I'll check if that may have been it

**Comment by sdepold** [comment]
I'll close this issue because the feed no longer exists. Feel free to re-open the ticket if you experience issues with other URLs
