### ISSUE TITLE
Filter not working?

### ISSUE THREAD

**Issue by mkhatree** [sdepold/jquery-rss#147]
I should provide some context first. My plan is to use jquery-rss to filter an RSS feed by keywords and limit it by a certain number of items. I've tried setting up the filter by number of items but the feed doesn't load at all. When I remove the filter code, the feed loads normally.

    <script>
      jQuery(function($) {
        $("#rss-feeds").rss("http://www.rssmix.com/u/8296676/rss.xml", {
          limit: 10,
          effect: 'slideFastSynced',
          filterLimit: 5,
          filter: function(entry, tokens) {
            return tokens.title.indexOf('my filter') > -1
          }
        })
      })
    </script>

**Comment by sdepold** [comment]
Seems to work fine with the following options:

```{
            filterLimit: 5,
            filter: function(entry, tokens) {
              return tokens.title.toLowerCase().includes('airline');
            }
          }```

<img width="603" alt="Screenshot 2019-10-16 at 15 29 24" src="https://user-images.githubusercontent.com/79163/66923755-b5724100-f029-11e9-9ddb-2cff95da5b9c.png">
