### ISSUE TITLE
Date outputting wrong

### ISSUE THREAD

**Issue by ForbiddenChunk** [sdepold/jquery-rss#149]
I've used the default demo code to get a feed through but I've noticed the date is coming through differently;

> [John Smith@2019-01-21T16:25:44.000Z]

Instead of;

> [Orman@Monday May 20th] Dark Accordion Style Navigation (PSD)

Any ideas why?

**Comment by sdepold** [comment]
@ForbiddenChunk It will only work if you add moment.js to your page
