### ISSUE TITLE
Service down

### ISSUE THREAD

**Issue by ValerieMichaud** [sdepold/jquery-rss#153]
Hi,
there's a 500 error.
Can you please investigate?

**Comment by sdepold** [comment]
Will do :/

**Comment by sdepold** [comment]
Works again!

**Comment by ValerieMichaud** [comment]
Thank you so much for the quick turn around!

**Comment by ValerieMichaud** [comment]
Down again today

**Comment by sdepold** [comment]
Hm. That’s rather unexpected. Will look into it. Sorry for the inconvenience!

**Comment by sdepold** [comment]
Seems to be due to an issue with the hoster. Will keep you posted!

**Comment by sdepold** [comment]
And its back!!

**Comment by valeriemichaud-k1** [comment]
Thanks!
