### ISSUE TITLE
Feature Request - Sorting and Enclosure Link

### ISSUE THREAD

**Issue by mortyobnoxious** [sdepold/jquery-rss#155]
Hi first of all thank you so much.

I have two problems or feature requests, I'm not sure :).

1. Sorting by date, new to old with multiple RSS feeds without separating each RSS feeds.
for example: `order: 'publishedDate',` sorts like this by seperating each feed:

![firefox_h055ocbq3t](https://user-images.githubusercontent.com/42044258/73046501-6edf7e80-3e83-11ea-8b78-15fee489e42a.png)

How can i sort by new without separating each feed?

2. I couldn't find a way to get this "enclosure > link" entry from `https://anchor.fm/s/11c5e0c/podcast/rss`.

![firefox_HgKjWPo8Ha](https://user-images.githubusercontent.com/42044258/73046520-874f9900-3e83-11ea-9e7a-e2a123023522.png)

**Comment by Ale-ASC** [comment]
Same issue about sorting
