### ISSUE TITLE
Callback fires multiple times

### ISSUE THREAD

**Issue by oakley808** [sdepold/jquery-rss#19]
Under some circumstances, the success or callback function will fire multiple times. (apparently "limit" + 1 times)

Here's a demo:
http://jsfiddle.net/2tqP9/3/

If I remove "`<p>{date}</p>`" from the entryTemplate, the callback is only fired once.
http://jsfiddle.net/uYtM8/1/

Weird.

**Comment by sdepold** [comment]
Seems to work by now.
