### ISSUE TITLE
Feedrapp.info is not working

### ISSUE THREAD

**Issue by Kirius88** [sdepold/jquery-rss#191]
Greetings!
Feedrapp.info has been down for several days now.
Will the site work again?

**Comment by bolod2006** [comment]
Hi, I have the same problem ( h.send(c.hasContent && c.data || null), ???? uery-1.6.4.min.js:4      net::ERR_NAME_NOT_RESOLVED
send @)

**Comment by aphwong** [comment]
The Feedrapp plugin is no longer support since May 13, 2023. and the hosting server also taken down
![image](https://github.com/sdepold/jquery-rss/assets/43560054/4febf840-a05c-40e7-8685-a9928d053b57)

**Comment by bolod2006** [comment]
Hi, where can you find out how to do it (host it on your server).
Thanks in advance.

**Comment by sdepold** [comment]
Long story short:

take the source code of feedr app, deploy them to some server, install dependencies, start the server, connect jquery-rss against it. I might take a bit of time in the next days to write a how to.

**Comment by sdepold** [comment]
FWIW: After a bit of chatting with different people, I'm bringing the server back online. It probably works as of now already. I'm going to do some more improvements going forward

**Comment by sdepold** [comment]
Closing this since we are back on track :)
