### ISSUE TITLE
Optionally use Superfeedr

### ISSUE THREAD

**Issue by julien51** [sdepold/jquery-rss#34]
Hey, Google does not have a great track record when it comes to RSS, would it be possible to add support to [Superfeedr](https://superfeedr.com/)'s API (similar to Google Feed's API) just in case as a failover mechanism? 

We (@superfeedr) would happily sponsor this work :)

**Comment by sdepold** [comment]
Feel free to provide a PR if this is still on your interest

**Comment by julien51** [comment]
Do you mind submitting guidelines on how to achieve this?

**Comment by sdepold** [comment]
Is superfeed compatible with the google feed API ?

**Comment by julien51** [comment]
Yes!

**Comment by sdepold** [comment]
Great. Well then it is as simple as this:

```
$("#rss-feeds").rss(
  "http://my-host.com/my-feed.xml",
  {
    ssl: true | false,
    host: 'superfeedrhost.com',
  }
)
```

Can you test that, ensure that all tests are passing and provide a PR that adds that as a note to the main readme?

**Comment by julien51** [comment]
Awesome! I'll do that later today :)

**Comment by sdepold** [comment]
:clap:

**Comment by julien51** [comment]
Hum. So, there are a bunch of things which make this fail :(
The most important one is that Superfeedr requires credentials: a username and a password. We have shim which makes [Superfeedr compatible with Google's API](http://blog.superfeedr.com/google-feed-api-alternative/), but I'm not sure how to integrate it with your library.
