### ISSUE TITLE
Struggling with display of a feed

### ISSUE THREAD

**Issue by cmcguff** [sdepold/jquery-rss#45]
I'm trying to get this feed to display - no errors, just not displaying.
http://www.ezypay.co.nz/feed/

I have validated with a couple of services, and it currently displays using a ruby reader that I want to move to client side.

I tried plugging it into this jsfiddle http://jsfiddle.net/jhfrench/AFHfn/ and I get the same results, have you got any clues?

**Comment by sdepold** [comment]
So just to make that sure: You want http://www.ezypay.co.nz/feed/ to get parsed right?

**Comment by cmcguff** [comment]
Yes, correct

**Comment by sdepold** [comment]
This is the magical line: https://github.com/sdepold/jquery-rss/pull/48/files#diff-2a8188e3ad34e48d1f2fda1d2e431485R16
