### ISSUE TITLE
Token usage for layoutTemplate

### ISSUE THREAD

**Issue by pjmagee** [sdepold/jquery-rss#52]
When defining a token the {token} keyword is not being replaced in the layoutTemplate. Example would be that I want to get the title or description of the feed and apply this in the overall template, not the entry template.

**Comment by sdepold** [comment]
Can you paste a self-contained test case in which it is not properly working?

**Comment by pjmagee** [comment]
It's not that's there is a bug. it's not implemented and this is just a suggestion. I made some of my own modifications to get it working on a project that I'm working on, but would not be good enough as a solution since it was more of a hack.

**Comment by sdepold** [comment]
Aaaah. Well that makes sense I guess :)

**Comment by pjmagee** [comment]
Yes, I needed to get things such as the RSS Feed title outside before the actual items. I'm surprised this hasn't already been asked for. Thanks for a great jquery plugin though! :+1:
