### ISSUE TITLE
Display inline

### ISSUE THREAD

**Issue by gholbrook** [sdepold/jquery-rss#53]
How do I display the unordered list with an inline style?

**Comment by sdepold** [comment]
Not sure if I understand the question. You can just style the rendered html with css?

**Comment by gholbrook** [comment]
Well, I've attempted to apply the style to the unordered list in as many ways as I could find, but it seems that the list is not being created like one would assume. I am able to replace the <ul> tags in the template with anything I want and achieve the same output. For instance, I can replace them with <water> and see the same feed.

**Comment by sdepold** [comment]
Can you please provide a code snippet? Which URL are you loading. Which styling do you want?

**Comment by sdepold** [comment]
Please reopen the ticket if you want to
