### ISSUE TITLE
Make moment dependency optional

### ISSUE THREAD

**Issue by jhfrench** [sdepold/jquery-rss#54]
As-is, jquery-rss cannot run without the moment date library introduced with https://github.com/sdepold/jquery-rss/pull/43.

Can the moment dependency be made optional? Not everyone uses Bower to manage dependencies; the date formatting is not desirable for all use-cases.

See also #23

**Comment by sdepold** [comment]
Hm. Yeah would make sense I guess. Though I think that if you aren't using Bower it is your job to add the necessary dependencies to the website where you want to use jquery-rss. Anyways: PR is welcome
