### ISSUE TITLE
not reading feed properly

### ISSUE THREAD

**Issue by ndimatteo** [sdepold/jquery-rss#55]
I'm having an issue where the script is not pulling in the latest post from the feed. It's skipping the first post and starting with the second one. You can see this here:

http://codepen.io/anon/pen/VLaoar

and here's a direct link to the feed where you can see the first post is visible: http://blog.knwm-llc.com/feed/

Why is this not working properly?

**Comment by sdepold** [comment]
Uhm ... what? Looks as if it is working for me

**Comment by ndimatteo** [comment]
Sorry about that. I ended up switching the feed URL to try and jig it and it seemed to start working again. Not really sure what the problem was. Possibly something with WordPress. I'll close this for now, if it comes up again I'll try to log it.

Thanks!
