### ISSUE TITLE
Moment.js: Deprecation Warning

### ISSUE THREAD

**Issue by Aurif3x** [sdepold/jquery-rss#56]
Moment.js is printing a warning to the console:
> "Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info."

This is being caused by line 218 of [jquery.rss.js](https://github.com/sdepold/jquery-rss/blob/gh-pages/src/jquery.rss.js#L218):
```javascript
date: moment(entry.publishedDate).format(this.options.dateFormat),
```
This usage of the moment() constructor is going to be deprecated soon. It is suggested that instead of dumping any date string into the constructor, one should instead use [String + Format](http://momentjs.com/docs/#/parsing/string-format/). For example:
```javascript
date: moment(entry.publishedDate, "MM-DD-YYYY").format(this.options.dateFormat),
```
Or, as is mentioned in https://github.com/moment/moment/issues/1407, if one _really_ needs to dump in random dates without specifying the format, another alternative is to let [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) handle it:
```javascript
date: moment(new Date(entry.publishedDate)).format(this.options.dateFormat),
```
For our use case -- an RSS feed reader -- I don't know if we can successfully use String + Format. RSS feeds are _supposed_ to have a standardized date format, as shown in the [RSS 2.0 specification](https://validator.w3.org/feed/docs/rss2.html):
> All date-times in RSS conform to the Date and Time Specification of RFC 822, with the exception that the year may be expressed with two characters or four characters (four preferred).
> Example: Sat, 07 Sep 2002 0:00:01 GMT

..but, my impression is that feeds in the wild [don't predictably follow this standard](http://rssdateformats.tumblr.com/), so anticipating what format the dates will use in any given feed is probably out of the question.

Should we go with letting Date parse the initial publishedDate string and hope for the best?
My guess is that we should, because Date is what Moment currently falls back to when the pubDate isn't ISO-8601 compliant. Using Date like this is a risky practice and doesn't always work, so they're removing this feature to wipe their hands clean of it. But, that doesn't stop _us_ from using it.

**Comment by jhfrench** [comment]
Related: #54
