### ISSUE TITLE
Google feed API 1.0 deprecated

### ISSUE THREAD

**Issue by eanbowman** [sdepold/jquery-rss#61]
I came here looking to see if there were an up-to-date version but it seems there isn't.

This project has been updated recently. Do you plan to continue to support the deprecated API or are there future plans for a rewrite which would circumvent the deprecated Google feed API and do the conversion in JS?

https://developers.google.com/feed/?hl=en
https://developers.google.com/feed/terms

**Comment by sdepold** [comment]
Is there an official replacement or are they just killing the api?

**Comment by eanbowman** [comment]
Good question. There doesn't seem to be an answer, but I'm currently coding my own solution to this using x2js: https://code.google.com/p/x2js/downloads/detail?name=x2js-v1.1.5.zip&can=2&q=

Wish me luck.

**Comment by sdepold** [comment]
I started my work on something similar some months ago too. So I would
replace the Google api with something else
Ean Bowman <notifications@github.com> schrieb am Mi., 29. Juli 2015 um
21:56:

**Comment by eanbowman** [comment]
I ended up changing the .load() prototype function to use an ajax call and x2js to parse it.

	RSS.prototype.load = function(callback) {
		if( typeof X2JS != 'undefined' ) {
			var x2js = new X2JS();
			var response = { 'responseData': { 'feed': { 'entries': [] } } };
			console.log( this.url );
			$.ajax({
				url: this.url
			}).done(function( data ) {
				response.responseData = x2js.xml_str2json( data );
				response.responseData.feed = response.responseData.rss;
				response.responseData.feed.entries = response.responseData.rss.channel.item;
				return callback(response);
			});
		} else {
			console.error('x2js library is required but the x2js object does not exist');
			return false;
		}
	}

The format x2js puts the XML in is slightly different. I had to copy the "description" to the "body" to get things to work for my implementation.

Hope this helps.

I don't want to create a pull request because I'm not sure of the robustness of the code I've created for use in other projects.

With a little work it could be adapted to be a complete replacement, however.

**Comment by eanbowman** [comment]
It's also important to note that unless you set the dataType to "text" it will automatically parse XML as a document element which is harder to work with.

    RSS.prototype.load = function(callback) {
        if( typeof X2JS != 'undefined' ) {
            var x2js = new X2JS();
            var response = { 'responseData': { 'feed': { 'entries': [] } } };
            console.log( this.url );
            $.ajax({
                url: this.url,
                dataType: 'text'
            }).done(function( data ) {
                response.responseData = x2js.xml_str2json( data );
                response.responseData.feed = response.responseData.rss;
                response.responseData.feed.entries = response.responseData.rss.channel.item;
                return callback(response);
            });
        } else {
            console.error('x2js library is required but the x2js object does not exist');
            return false;
        }
    }

**Comment by sdepold** [comment]
So I worked a bit on the project I was starting a while ago and will try to use that: https://github.com/sdepold/feedr
