### ISSUE TITLE
feedrapp.info and SSL support

### ISSUE THREAD

**Issue by jotarun** [sdepold/jquery-rss#64]
It seems that feedrapp.info doesn't support SSL?

**Comment by sdepold** [comment]
Hi @jotarun,

good catch. Was just looking into it and noticed that SSL endpoints on Heroku cost 20$/month. Will think about this problem.

**Comment by sdepold** [comment]
OK so first step is to actually use www.feedrapp.info instead of feedrapp.info. Once that's done I will try to enable SSL on www.feedrapp.info

**Comment by sdepold** [comment]
v3.1.0 should allow SSL again :)
