### ISSUE TITLE
Feedr: Unterminated string literal

### ISSUE THREAD

**Issue by Aurif3x** [sdepold/jquery-rss#66]
So, I'm trying to upgrade to v3.0.1, and it seems to work everywhere but one place. In one instance, where we're using jquery-rss to fetch posts from a Wordpress blog, the script crashes with the following console message: "SyntaxError: unterminated string literal".

This is the request causing the error: http://www.feedrapp.info/?callback=jQuery110203348644026184171_1440446349851&q=http%3A%2F%2Fpennlibnews.wordpress.com%2Fcategory%2Fpenn-libraries%2Ffeed%2F&num=3&_=1440446349852
https://github.com/sdepold/jquery-rss/releases/tag/v3.0.1
(I have no idea if this link will expire; sorry if it does.)

Any idea why this is happening? I can't tell where the unterminated string is, or why it might be there.

**Comment by sdepold** [comment]
You mean when you open that url you are receiving an error?

**Comment by sdepold** [comment]
Can you also please provide the respective jquery-rss call?

**Comment by Aurif3x** [comment]
Here, I'll make it temporarily live again so you can see the error:
http://www.library.upenn.edu/
(You can see the error in the console.)

We're using jquery-rss for two feeds on the page: news and events. The news feed, which is a feed of Wordpress posts, is breaking.

We've abstracted our site-wide jquery-rss settings into this file:
http://www.library.upenn.edu/scripts/feedreader/pennFeedReader.js

And the call for the news feed is here:
http://www.library.upenn.edu/scripts/feedreader/readNews.js

**Comment by sdepold** [comment]
hm when I open the URL I'm not getting any error. Which browser are you using?

**Comment by Aurif3x** [comment]
It happens to me in Chrome and Firefox.

**Comment by sdepold** [comment]
ah ok I can see that error now in firefox

**Comment by sdepold** [comment]
So inside your feed there is a invisible character which kills the string :o That is amazing! Guess I will filter that characters out

**Comment by sdepold** [comment]
I think it works now. Can you check?

**Comment by Aurif3x** [comment]
Yes, it works! Thank you so much! :smile:

**Comment by sdepold** [comment]
Glad to hear that!
Ivan Goldsmith <notifications@github.com> schrieb am Mi., 26. Aug. 2015 um
16:05:
