### ISSUE TITLE
Truncate {title} objects by chatacter number

### ISSUE THREAD

**Issue by Castellanox7** [sdepold/jquery-rss#69]
Good morning,

Is there any support for wanting to truncate the {titles} retrieved by the RSS feed? 

For example, "This is a Test Post", becomes "This is a Test..."

Thank you.

**Comment by sdepold** [comment]
Good morning. You basically want this:

```
$('#foo').rss({
  entryTemplate: '<p>{truncatedTitle}</p>',
  tokens: {
    truncatedTitle: function (entry, tokens) {
      return tokens.title.slice(0, 5) + '...';
    }
  }
});
```

This will give you the first 5 chars of the title.

**Comment by Castellanox7** [comment]
Awesome. Thanks, Sd!
