### ISSUE TITLE
Can't use dateFormatFunction option when moment.js is present

### ISSUE THREAD

**Issue by mynameiscorey** [sdepold/jquery-rss#72]
So I wanted to use moment.js' Time from now method to get a '5 minutes ago' version of the date of an rss item. However this can't (as far as I can tell) be done with a format string and requires you to do something like this:

```javascript
moment(date).fromNow();
```

in the dateFormatFunction option. JQuery-rss doesn't call this function if moment.js is present though, so you can't do any manipulation of the date with moment.js outside of setting a format string in dateFormat.

see here:

```javascript
    // If moment.js is available, use it to format the date.
    if (typeof moment !== 'undefined') {
      this.formattedDate = moment(new Date(entry.publishedDate)).format(this.options.dateFormat);
    } else {
      // Otherwise, if a custom formatting function is provided, use that.
      if (this.options.dateFormatFunction) {
        this.formattedDate = this.options.dateFormatFunction(entry.publishedDate);
      } else {
        // If all else fails, just use the date as-is.
        this.formattedDate = entry.publishedDate;
      }
    }
```

**Comment by mynameiscorey** [comment]
Pull request for fix here - https://github.com/sdepold/jquery-rss/pull/73

C.

**Comment by sdepold** [comment]
Fixed in latest version
