### ISSUE TITLE
LayoutTemplate: '{entries}',

### ISSUE THREAD

**Issue by Djole728** [sdepold/jquery-rss#76]
I used older version of jquery.rss.js to create a Currency exchange.

This is my code http://jsfiddle.net/Djole728/k4w0d059/.

It's look like this 

![kursna lista](https://cloud.githubusercontent.com/assets/7227364/11558459/3a52711e-99b3-11e5-9d24-6b41f80c5dda.jpg)

Everything works great.

Now I change jquery.rss.js to last version and it does not work. There is no errors in console, and it does not show anything.

When i delete my custom layoutTemplate:  layoutTemplate: '{entries}', then it's using default layoutTemplate: layoutTemplate: 'ul {entries} ul', and it's looks like this

![currenty](https://cloud.githubusercontent.com/assets/7227364/11558679/55cae57e-99b4-11e5-9a8a-b2817c35a218.jpg)

It's doesn't should look like this, because he put ul in tbody, but it show my everything else properly. When i delete ul from layoutTemplate, then it stop working .

I look at example https://github.com/sdepold/jquery-rss/blob/gh-pages/examples/accordion.html and in this example layoutTemplate: '{entries}', is used, and example doesn't work.

When i delete layoutTemplate: '{entries}', it's start working,

Is it possible that layoutTemplate: '{entries}', is not working properly?

Thank You in Advance.

**Comment by sdepold** [comment]
why did you close the issue?

**Comment by Djole728** [comment]
I forgate to mention that i use jquery.rss and the same rss feed to load those two dropdown lists.
That also stop working.

![dropdown](https://cloud.githubusercontent.com/assets/7227364/11574321/42a79436-9a0b-11e5-9f8f-bb1ef8b19e78.JPG)

For table, i also try to put instead of layoutTemplate: '{entries}' this
![table](https://cloud.githubusercontent.com/assets/7227364/11574386/afc53ef6-9a0b-11e5-910d-e00474b0a76e.JPG)

that didn't work.

Than i tried with this

![tbody](https://cloud.githubusercontent.com/assets/7227364/11574409/d64fa85e-9a0b-11e5-86ba-63c9407a37c5.JPG)

That worked in IE, but not in Chrome and Firefox.

So i am not sure is my rss feed is good.

It is strange, because, when i write console.log(entry), it show data, so i think that the data is there, just it can show them for some reason.

All this happend whan i change the version of jquey.rss.

At the end, i used onData function, and i load data in table and dropdown from her,

I can reopen the issue, but i my not sure is jquey.rss is problem or feed, or my code.
It is strange to me that no one has problem with layoutTemplate: '{entries}' before me. I guess lot of people using layoutTemplate: '{entries}'.

**Comment by alexiskattan** [comment]
+1 layoutTemplate: "{entries}" doesn't work for me

**Comment by Insnee** [comment]
+1 layoutTemplate: "{entries}" doesn't work for me

**Comment by sdepold** [comment]
@alexiskattan @Insnee @Djole728 Can you try #83 ?

**Comment by Djole728** [comment]
Now it's render the view, but i think there is one problem.

Let's say that my container where i want to insert entries is table tag.

I have this

$("#ObukeADS").rss("http://www.cbbh.ba/kursna_bs.xml", {
        limit: 3,
        layoutTemplate: '{entries}',
        entryTemplate: '<tr><td class="vijestiVijecaLink">{naslov}</td><td>test</td></tr>',
        tokens: {
            naslov: function (entry, tokens) { console.log(entry); return entry.title },            
        }
    });
}

and container is this 

"<table id ="ObukeADS">
<tbody>
<td>Naslov</td>
<td>Test</td>
</tbody>
</table>"

**Comment by sdepold** [comment]
OK. Let me try to fix it.

**Comment by sdepold** [comment]
Alright. Nao! Please try again :)

**Comment by Djole728** [comment]
Work like a charm :) Thanks

**Comment by sdepold** [comment]
Released as 3.2.1
