### ISSUE TITLE
SSL feed not working

### ISSUE THREAD

**Issue by rjn71** [sdepold/jquery-rss#92]
Hi

This doesn't seem to work for SSL feeds. for e.g. https://www.bis.org/list/bis/index.rss. I tried in plunkr setting ssl option to true, but doesn't work. Is this a limitation?

Thanks
![sslfeed](https://cloud.githubusercontent.com/assets/17086755/12874261/31f93b58-cdc8-11e5-8121-5a35148784bb.JPG)

**Comment by sdepold** [comment]
Hm the problem might be the invalidity of the feed itself: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.bis.org%2Flist%2Fbis%2Findex.rss

Please note that you only need to enable the ssl option if you are running on an SSL page. It's not for rendering feeds that are hosted on an SSL endpoint.

**Comment by rjn71** [comment]
I'm not so sure. If I open the feed in IE, it seems to work fine. I've tried using another jquery plugin, that seems to bring the result - http://jquery-plugins.net/FeedEk/FeedEk_demo.html

**Comment by duke90** [comment]
I have similar problem. I'm using jquery-rss in an ssl-hosted page, so I have to enable ssl:true option, otherwise the browser blocks my request. because of mixed content (The feed I'm reading is hosted on a non-ssl server)
Anyway, I tried this in a plnkr, and if i enable ssl, the request sent by jquery-rss goes to https://feedrapp.herokuapp.com, and the response status is 503.
If I do not enable ssl, the request goes to http://www.feedrapp.info, and the response status is 200.
So I think the problem is somewhere around your ssl hosted service...

**Comment by sdepold** [comment]
Oh crap! I will fix that. I think you can set a host to
https://feedrapp.info and enable ssl
László Huszta <notifications@github.com> schrieb am Do. 22. Juni 2017 um
14:43:

**Comment by duke90** [comment]
Hello, I removed my previous comment, because I realised what caused my problem. Simply my version of the rss plugin was outdated. After updating to the newest, the ssl requests are nicely going to feedrapp.info.

**Comment by duke90** [comment]
At the moment feedrapp.info is down, it responds with status code 500. Are you aware of this problem?

**Comment by sdepold** [comment]
Is it better now?
László Huszta <notifications@github.com> schrieb am Fr. 23. Juni 2017 um
15:52:

**Comment by sdepold** [comment]
Perfect. I also figured that later

László Huszta <notifications@github.com> schrieb am Fr. 23. Juni 2017 um
15:51:

**Comment by duke90** [comment]
Definitely better! :smile: All the feeds I'm using are working fine. Thanks for the quick response, and fix! Big respect!

**Comment by sdepold** [comment]
🙂 I didn't fully figure out yet why this happens from time to time but I
will investigate in it
László Huszta <notifications@github.com> schrieb am Fr. 23. Juni 2017 um
16:08:

**Comment by duke90** [comment]
As I understand the feedrapp server is a node application. Do you use pm2 or foreverjs or similar process management tool to ensure it runs continuously? - obviously just a workaround, not a solution for the errors :slightly_smiling_face:

**Comment by sdepold** [comment]
Pm 2 I use
László Huszta <notifications@github.com> schrieb am Fr. 23. Juni 2017 um
16:17:
