### ISSUE TITLE
div Not displaying anything

### ISSUE THREAD

**Issue by SMUchacz** [sdepold/jquery-rss#94]
Hello,

I have integrated the code into a webpage but it is not displaying the rssfeed div

Thoughts?

**Comment by sdepold** [comment]
Can you show me some code?

**Comment by sdepold** [comment]
Is it possible that the site that you are running is using ssl?

**Comment by SMUchacz** [comment]
I switched ssl to true, but it still did not display anything.

My html:
`<script src="lib/jquery-1.6.4.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
        <script src="src/jquery.rss.js"></script>
        <script>
            jQuery(function($) {
                $("#rss-feeds").rss("http://blog.spotmarketing.ca/rss.xml", {
                    limit: 3,
                    effect: 'slideFastSynced'
                })
            })
        </script>`

My Javascript:
this.options = $.extend({
      ssl: false,
      host: 'www.feedrapp.info',
      limit: 3,
      key: null,
      layoutTemplate: '<div class="row"><div class="blog-posts">{entries}</div></div>',
      entryTemplate: '<div class="post-item col-md-4"><div class="post-image"><a href="{url}">{teaserimage}</a></div><article class="post-content main-border"><div class="post-info-container"><div class="post-info"><i class="fa fa-book post-icon"></i><h2><a href="{url}}">{title}}</a></h2><ul class="post-meta"><li class="meta_date"><i class="fa fa-clock-o"></i>{date}</li></ul></div></div><p>{shortBodyPlain}</p><div class="bottom_tools"><a class="meta_comments f-left shape" href="{url}#comments"><i class="fa fa-comments"></i></a><a class="f-right more_btn shape" href="{url}">Read more</a></div></article></div>',
      tokens: {},
      outputMode: 'json',
      dateFormat: 'dddd MMM Do',
      dateLocale: 'en',
      effect: 'show',
      offsetStart: false,
      offsetEnd: false,
      error: function () {
        console.log('jQuery RSS: url doesn\'t link to RSS-Feed');
      },
      onData: function () {},
      success: function () {}
    }, options || {});

**Comment by SMUchacz** [comment]
`this.options = $.extend({
      ssl: true,
      host: 'www.feedrapp.info',
      limit: 3,
      key: null,
      layoutTemplate: '<div class="row"><div class="blog-posts">{entries}</div></div>',
      entryTemplate: '<div class="post-item col-md-4"><div class="post-image"><a href="{url}">{teaserimage}</a></div><article class="post-content main-border"><div class="post-info-container"><div class="post-info"><i class="fa fa-book post-icon"></i><h2><a href="{url}}">{title}}</a></h2><ul class="post-meta"><li class="meta_date"><i class="fa fa-clock-o"></i>{date}</li></ul></div></div><p>{shortBodyPlain}</p><div class="bottom_tools"><a class="meta_comments f-left shape" href="{url}#comments"><i class="fa fa-comments"></i></a><a class="f-right more_btn shape" href="{url}">Read more</a></div></article></div>',
      tokens: {},
      outputMode: 'json',
      dateFormat: 'dddd MMM Do',
      dateLocale: 'en',
      effect: 'show',
      offsetStart: false,
      offsetEnd: false,
      error: function () {
        console.log('jQuery RSS: url doesn\'t link to RSS-Feed');
      },
      onData: function () {},
      success: function () {}
    }, options || {});
`

**Comment by sdepold** [comment]
This seems to work:

```
      $("#rss-feeds").rss("http://blog.spotmarketing.ca/rss.xml",
      {
        ssl: true,
        limit: 3,
        layoutTemplate: '<div class="row"><div class="blog-posts">{entries}</div></div>',
        entryTemplate: '<div class="post-item col-md-4"><div class="post-image"><a href="{url}">{teaserImage}</a></div><article class="post-content main-border"><div class="post-info-container"><div class="post-info"><i class="fa fa-book post-icon"></i><h2><a href="{url}}">{title}}</a></h2><ul class="post-meta"><li class="meta_date"><i class="fa fa-clock-o"></i>{date}</li></ul></div></div><p>{shortBodyPlain}</p><div class="bottom_tools"><a class="meta_comments f-left shape" href="{url}#comments"><i class="fa fa-comments"></i></a><a class="f-right more_btn shape" href="{url}">Read more</a></div></article></div>',
        dateFormat: 'dddd MMM Do',
        dateLocale: 'en',
        effect: 'show'
      })
```

Note that I 
- removed the host from the options
- changed the token `teaserimage` to `teaserImage`

:)

**Comment by SMUchacz** [comment]
I have followed your changes exactly and I am still not seeing anything, here is a live version of the webpage I am working on: http://spotmarketing.ca/Demo/index.html

I will also attach the two files
[jquery-rss.zip](https://github.com/sdepold/jquery-rss/files/128093/jquery-rss.zip)

**Comment by sdepold** [comment]
Why did you modify jquery-rss.js ? Please take the latest version.

**Comment by SMUchacz** [comment]
oh, I assumed that the options had to be modified in there.

**Comment by sdepold** [comment]
Naah. :D The site should work properly if you use the original jquery-rss.js file and initialize it as stated here https://github.com/sdepold/jquery-rss/issues/94#issuecomment-183181993

Btw. since your site is not using ssl you can also turn ssl off again.

**Comment by SMUchacz** [comment]
Ah yes, now it is displaying. Thank you for your assistance!

**Comment by sdepold** [comment]
Cool :) You are welcome
