### ISSUE TITLE
getting href of xml entry in custom token

### ISSUE THREAD

**Issue by JanKopietzGit** [sdepold/jquery-rss#97]
hi there,

first of all thanks for your work on this great little plugin. I've ran into an issue with the following rss feed: https://www.haufe-akademie.de/blog/new-rss-feed/

I'm trying to get the href attribute of the atom:link xml element within a custom token function. I've tried a lot with no result (mostly "is undefined" error). My token functions looks like this:

`postImage: function(entry) {
                return entry['atom:link'].attr('href');
            }`

right now I'm stuck and confused about the functionality of the custom tokens. any suggestions? I know the feed isn't valid. There is no option to change this at the moment.

Greetings,
Jan

**Comment by sdepold** [comment]
:wave: This is what the feed parser returns http://www.feedrapp.info/?q=https://www.haufe-akademie.de/blog/new-rss-feed/

If the content you want to have is not in there it'd be best to file a ticket there and to pinpoint which information you would need. The git repo is here: https://github.com/sdepold/feedrapp

**Comment by sdepold** [comment]
Are you looking for the link?

**Comment by JanKopietzGit** [comment]
Thanks for reply. I'm looking for the href value of this rss element:

`<atom:link href="https://www.haufe-akademie.de/blog/wp-content/uploads/2016/03/HR-und-die-digitale-Transformation.jpg" rel="image" type="image/jpeg" />`

I see feedr is not parsing this element so I'll file a ticket at feedrapp. Or are there any other suggestions?

Greeting,
Jan

**Comment by sdepold** [comment]
Nope I think that's the best option :)

**Comment by JanKopietzGit** [comment]
I solved the issue on another way: just replaced some string characters in a custom token from the teaserImageUrl to get the high-res img src. So no need to parse the atom:link element.

Here's the custom token, if anyone run into the issue to remove characters from the teaserImageUrl:

`postImage: function(entry, tokens) {
                return tokens.teaserImageUrl.replace('-110x96', '');
            }`


Anyway thanks for the help.

**Comment by sdepold** [comment]
Cool :)
